# Architecture identifier.
arch = "riscv64"
# Platform identifier.
platform = "riscv64-starfive"
#
# Platform configs
#
[plat]
# Platform family.
family = "riscv64-starfive" # str

# Base address of the whole physical memory.
phys-memory-base = 0x4000_0000
# Size of the whole physical memory.
phys-memory-size = 0x1000_0000
# Base physical address of the kernel image.
kernel-base-paddr = 0x4020_0000
# Base virtual address of the kernel image.
kernel-base-vaddr = "0xffff_ffc0_4020_0000"
# Linear mapping offset, for quick conversions between physical and virtual
# addresses.
phys-virt-offset = "0xffff_ffc0_0000_0000"
# Offset of bus address and phys address. some boards, the bus address is
# different from the physical address.
phys-bus-offset = 0 # uint
# Kernel address space base.
kernel-aspace-base = "0xffff_ffc0_0000_0000" # uint
# Kernel address space size.
kernel-aspace-size = "0x0000_003f_ffff_f000" # uint

[devices]
# MMIO regions with format (`base_paddr`, `size`).
mmio-regions = [
    [0x0c00_0000, 0x0400_0000], # PLIC
    [0x1000_0000, 0x1_0000],    # UART0 (console)
    [0x1001_0000, 0x1_0000],    # UART1
    [0x1002_0000, 0x1_0000],    # UART2
    [0x1003_0000, 0x1_0000],    # UART3
    [0x1004_0000, 0x1_0000],    # UART4
    [0x1005_0000, 0x1_0000],    # UART5
    [0x1601_0000, 0x1_0000],    # SDIO0
    [0x1602_0000, 0x1_0000],    # SDIO1
    [0x1603_0000, 0x1_0000],    # DWMAC0 (ethernet@16030000)
    [0x1604_0000, 0x1_0000],    # DWMAC1 (ethernet@16040000)
    # [0x1304_0000, 0x1_0000],    # GPIO
] # [(uint, uint)]

virtio-mmio-regions = [
    # [0x8200_1000, 0x1000], # tdes
    # [0x8200_2000, 0x1000], # rdes

    # [0x8201_0000, 0x10000], # txbuffer
    # [0x8202_0000, 0x10000], # rxbuffer

    # [0x1981_0000, 0x10000], # clock-controller isp
    # [0x1302_0000, 0x10000], # clock-controller sys   4df0300
    # [0x1023_0000, 0x10000], # clock-controller stg   4e10000
    # [0x1700_0000, 0x10000], # clock-controller aon
    # [0x295c_0000, 0x10000], # clock-controller vout

    # [0x0201_0000, 0x1000], # cache_flush
] # [(uint, uint)]
# Base physical address of the PCIe ECAM space.
pci-ecam-base = 0x3000_0000 # uint
# End PCI bus number (`bus-range` property in device tree).
pci-bus-end = 0xff # uint
# PCI device memory ranges (`ranges` property in device tree).
pci-ranges = [
    [0x0300_0000, 0x1_0000],        # PIO space
    [0x4000_0000, 0x4000_0000],     # 32-bit MMIO space
    [0x4_0000_0000, 0x4_0000_0000], # 64-bit MMIO space
] # [(uint, uint)]


# Timer interrupt frequency in Hz.
timer-frequency = 4_000_000 # uint

# VisionFive 2 doesn't use goldfish RTC
# rtc-paddr = 0x10_1000 # uint
